# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          
      - name: Fetch and checkout before obfuscate
        run: |
          git fetch
          git checkout public
          git merge master --force
          
      - name: Ensure JS files start out unobfuscated
        run: |
          git checkout HEAD hideout-vis.js
          git checkout HEAD vis-network.min.js
          git checkout HEAD loc/en-US.js
          git checkout HEAD loc/ru-RU.js
          cat hideout-vis.js

      # Runs a set of commands using the runners shell
      - name: Obfuscate
        uses: florrdv/JS-Obfuscator@v1.0.2
        
      - name: Stage changes
        run: |
          git add .
          git status
      
      - name: Configure, commit, and push
        run: |
          git config --global user.email "brad@malloy.io"
          git config --global user.name "GitHub Actions"
          git commit -m "Creating an obfuscated commit thru GH action..."
          git push
      
      - name: Final status check
        run: |
          git status
          git log
